### ISSUE TITLE
index.php returns white page

### ISSUE THREAD

**Issue by Brahmachari** [keslar/yourls-multi-user#3]
Hi, thank you for your work!
After having installed the plugin in an unmodified state and calling https://rmo.li/user/plugins/multi-user/index.php I get a white page.

Debugging:
Fatal error: Cannot redeclare captchaEnabled() (previously declared in /home/eremosc1/public_html/rmo.li/user/plugins/multi-user/mufunctions.php:51) in /home/eremosc1/public_html/rmo.li/user/plugins/multi-user/mufunctions.php on line 54

Line 50: function captchaEnabled
After having set lines 50-54 on comment the script runs trough to line 127.

Fatal error: Cannot redeclare validEmail() (previously declared in /home/eremosc1/public_html/rmo.li/user/plugins/multi-user/mufunctions.php:64) in /home/eremosc1/public_html/rmo.li/user/plugins/multi-user/mufunctions.php on line 127

What's wrong there? Looking forward for your help. Thanks!

**Comment by keslar** [comment]
In the .../multi-user/index.php comment out the lines that include mufunctions.php

**Comment by Brahmachari** [comment]
OK, no fatal error anymore.
https://rmo.li/user/plugins/multi-user/index.php?act=login is shown.
Of course, login does not work without mufunctions.php
 
next? Thank you.

-----Original Message-----

**Comment by Brahmachari** [comment]
How to proceed, please?
Thank you.

**Comment by jacek-jonca** [comment]
If you go to index.php and at the beginning of the file replace all include statements with include_once it should work.

**Comment by dabates** [comment]
I'm working on a fork of this since this and the original seems to be abandoned.. 

If @keslar want's a merge request, let me know.. we are using this in conjunction with another plugin we are creating.. so I need to make sure this works correctly. 

Just FYI

**Comment by keslar** [comment]
As jacek-jonca suggested, changed include statements to include_once .

**Comment by dabates** [comment]
> 
> 
> As jacek-jonca suggested, changed include statements to include_once .

There were actually a few other things I had to change to deal with the newest version of YOURLS.  Namedly some Database issues, a global that was missing and the redefinition of already defined constants..
